### ISSUE TITLE
Running FRASER for 4 bam files

### ISSUE THREAD

**Issue by jjyotikataria** [gagneurlab/FRASER#10]
@ischeller @c-mertes 
I ran FRASER pipeline with the cutoffs for results as follows. I wanted to see all the results and will apply manual filtering later.

res <- results(fds, zScoreCutoff=NA, padjCutoff=NA, deltaPsiCutoff=NA)

I got 8 lakh 37k entries
However, the p value range I found in the total results was from 0.73 to 1
                     p adj = 1 always for all rows
                     delta psi = 0 always for all rows
                     zscore = ranging from 1.5 to -1.5

I am not sure how to report the significantly present aberrant events. Can you provide some guideline?

**Comment by ischeller** [comment]
Just 4 samples is not enough to find aberrant splicing events. That's why the results you got here are not very useful. We recommend to use at least 30 samples for FRASER. 
To identify aberrant splicing events, we recommend an adjusted p-value cutoff of 0.05 or 0.1 together with a cutoff on the delta psi of 0.3 (this depends on your specific application) to detect significant splicing events with a strong effect.

**Comment by jjyotikataria** [comment]
@ischeller Hi. We are actually looking for aberrant splicing events in each sample. Lets say if don't have any control or case groups, for example we are doing rna sequencing for one patient and we are trying to find out the aberrant events  present in the sample. It is difficult many a times to get normal samples in clinical studies. Is there any way we can get aberrant splicing event for a single sample?

**Comment by ischeller** [comment]
Hi @jjyotikataria , we need at least 30 samples to confidently model the expected psi values, accounting for latent variables that may be present in the data. If you have only 4 samples, this will not work well. If you only have those 4 samples, you could combine them with publicly available cohorts like GEUVADIS or GTEx, preferably with samples from the same tissue as yours.

**Comment by c-mertes** [comment]
For more details on how to augment your dataset with external counts have a look at our DROP paper at Nature Protocols: https://www.nature.com/articles/s41596-020-00462-5 Hope this helps.
