### ISSUE TITLE
Question regarding the sample size of FRASER

### ISSUE THREAD

**Issue by lyj95618** [gagneurlab/FRASER#21]
Hello. I am new to bioinformatics and curious how to use FRASER to look for aberrant splicing events in a single sample (If this is possible)? I know the recommended sample size is 30. Lets say if I run 1 patient sample and 30 normal samples from GTEx together, will this sufficient enough to look for aberrant splicing events in my sample?
Any help will be much appreciated.

**Comment by c-mertes** [comment]
Dear @lyj95618, this is related to #10 

FRASER needs some data to fit its model. Having just one sample will make it hard. Merging it with GTEx sample can help but we would recommend having at least 10 samples to merge with GTEx. The problem with 1 sample is that any technical bias will pop up as an outlier event, as the model can not model the covariates between the GTEx samples and your single sample.

For more details on how to merge external datasets, you can have a look at our new protocol https://www.nature.com/articles/s41596-020-00462-5

**Comment by lyj95618** [comment]
Thank you very much for your detailed explanation!
