### ISSUE TITLE
Offline use of countSplitReads

### ISSUE THREAD

**Issue by AEstebanMar** [gagneurlab/FRASER#50]
Hello, I am having some problems running your package due to (lack of) internet connectivity. 

Our group works in a network which blocks internet connection for security reasons. We can download any necessary resources locally, but when it comes to execution we have no connection available.

The issue comes with the countSplitReads function, which ends up calling get_chrom_info_for_registered_UCSC_genome from genomeInfoDb. This function attempts to download chromInfo.txt.gz, which is not possible in our setting.

An issue was submitted to GenomeInfoDb describing a related problem (https://github.com/Bioconductor/GenomeInfoDb/issues/26), and a solution was implemented to the package [(quote reply)](https://github.com/Bioconductor/GenomeInfoDb/issues/26#issuecomment-1277049426). Would it be possible for countSplitReads to have a parameter passed down through function calls to use this "offline mode"? If so, we could first download chromosome information locally and access that cache in offline execution.

Thank you,
Álvaro.

**Comment by drewjbeh** [comment]
Hi @AEstebanMar,

I am trying to identify the source of the error but am having a hard time. `countSplitReads` doesn't actually call `get_chrom_info_for_registered_UCSC_genome` as you mention. I am looking for other function calls that try to access this info online. As part of that search, I have run FRASER with the test data on my local machine and disabled internet connectivity when doing so. This completes successfully.
A few things that may be the issue; which version of FRASER are you running? Which species/genome does the data originate from? 
It would also be very useful to send some other things here to help debugging. For example; the list of commands you use up to the point you get an error, and the traceback and error output at the problematic step. Thanks!

**Comment by AEstebanMar** [comment]
Hello, @drewjbeh,

I have updated FRASER since I originally posted the issue, and did not think to undo my temporary fix. I've tested it again after reading your answer, this time removing my fix, and it works properly. It seems the issue has been fixed at some point since my original question.

Thank you, marking as solved.
