### ISSUE TITLE
install devtools

### ISSUE THREAD

**Issue by Eyulaochen** [gagneurlab/FRASER#57]
error in installing devtools

ft_cache.h:9:10: fatal error: ft2build.h: No such file or directory

**Comment by drewjbeh** [comment]
@Eyulaochen  It seems there are some missing packages for systemfonts on your system. See the solution [here](https://stackoverflow.com/questions/68094530/fatal-error-installing-systemfonts-in-jupyter-r-docker) with more details [here](https://github.com/r-lib/systemfonts/issues/50)

**Comment by c-mertes** [comment]
As this is answered, I will close this issue.
