### ISSUE TITLE
Error in if (nPcs > ncol(Matrix))

### ISSUE THREAD

**Issue by gianfilippo** [gagneurlab/FRASER#60]
Hi,

I am trying to run the demo data, as described in the tutorial, but when I run
fds <- FRASER(fds, q=c(psi5=2, psi3=3, theta=3))

I get the following error
Mon Dec 11 18:39:27 2023: Fit step for: 'jaccard'.
Mon Dec 11 18:39:27 2023: Running fit with correction method: PCA
Mon Dec 11 18:39:28 2023: Computing PCA ...
Error in if (nPcs > ncol(Matrix)) { : the condition has length > 1

I am running "R version 4.3.0"

Thanks

**Comment by drewjbeh** [comment]
Hi there,

Thanks for pointing this out. There is an error in this example copde in the vignette which comes from some changes in the new version of FRASER which aren't reflected in this documentation. As we fit a separate autoencoder for each splice metric (defaults: jaccard metric for **FRASER 2.0**, psi_5, psi_3 and theta metrics for **previous FRASER versions**), it's possible to specify different dimensions for each splice metric that should be fitted. Generally we recommend to determine this parameter with the `optimHyperParams()` function, but it's possible also manually specify values if you want to skip this time-intensive step, as in the example in the vignette. So basically, you would need to only add a parameter for `jaccard` in the function and it should work, for example:
`fds <- FRASER(fds, q=c(jaccard=2, psi5=2, psi3=2, theta=2), iterations=2)`

See [this](https://github.com/gagneurlab/FRASER/blob/master/R/example_functions.R) file for more example fucntion calls.

Hope that helps!

**Comment by gianfilippo** [comment]
Hi,

thanks. It works now.

Best
