### ISSUE TITLE
Can't run countRNAData

### ISSUE THREAD

**Issue by mmartinezj** [gagneurlab/FRASER#67]
Hello, 
First of all, thank you for devoloping this tool. Secondly, after trying to run the countRNAData function, the following error appears: "Error: useNames = NA is defunct. Instead, specify either useNames = TRUE or useNames = FALSE.". After looking up the reason behind this, seems that the version 1.2 of the matrixStats package causes this error. If I could have some help on how should I proceed in order to be able to use countRNAData function with this happening, I would really appreciate it. (I have tried to downgrade the matrixStats version, but haven't been lucky with it either). Thank you in advance.

Best regards,

Miriam

**Comment by laetitiarialland** [comment]
Hello, 
I just install FRASER on R 4.1.2 and I am facing the same issue. Did you find any solution ? 
Thank you so much for your help !!
Kind regards 

Laëtitia

**Comment by AtaJadidAhari** [comment]
Hi, there is indeed a compatibility problem with `MatrixGenerics` and base R version. Using R version 4.3.0 solves this issue for me. Can you try to redo your analysis with this version? 
Running functions such as `rowMaxs` with `useNames = TRUE` is another way to solve the problem, but there are several usages of such functions and it's a bit tedious to change all of them. 

Best,

Ata

**Comment by laetitiarialland** [comment]
Hello !
I try with R4.3.3, and it works,  !!
Thanks you so much @AtaJadidAhari


Kind regards,

Laëtitia
