### ISSUE TITLE
Go back to raw data after using FRASER::results()

### ISSUE THREAD

**Issue by fburdet** [gagneurlab/FRASER#83]
Hello,

I would like to see the raw data that was used to generate p-values and z-scores in the results() table. For example, fds_filtered@assays@data[["psi5"]], and see the values by sample.

However, I don't seem to be able to get back to it using the concatenation of seqnames : ranges. Are these coordinates changed somehow when running res() ?

Or is it again a problem of species?

Thanks in advance!

**Comment by vyepez88** [comment]
Hi, yes, try:
`assays(fds)$psi5`
You can see all the assays using:
`names(assays(fds))`
