### ISSUE TITLE
Adapt the script for mouse?

### ISSUE THREAD

**Issue by fburdet** [gagneurlab/FRASER#84]
Hello,

First of all, is this code still maintained? I received absolutely no news despite writing directly to the author.

My question is, is it possible to adapt the code for mouse data?

I tried to use
library(TxDb.Mmusculus.UCSC.mm10.knownGene)
library(org.Mm.eg.db)

but I get errors about chromosome length, I suspect it's hardcoded to use human, is it the case?

It makes most of the plotting functions not usable, as they seem to depend on this annotation.

**Comment by cayyya** [comment]
I have similar problem but with Arabidopsis and I cant even reach the plotting stage.
fds <- countRNAData(settings) yields following error:
Error in .replace_seqlevels_style(x_seqlevels, value) : 
  found no sequence renaming map compatible with seqname style "TAIR9" for this object

Is there any hint how to set up the workflow for Arabidopsis?

**Comment by vyepez88** [comment]
Hi, sorry for the late reply. Yes, at this stage, we only support human.
