### ISSUE TITLE
 All adjusted p-values at 1

### ISSUE THREAD

**Issue by Cam-eraaa** [gagneurlab/FRASER#88]
Dear FRASER2 team,

I am currently trying to use FRASER2 to analyse RNAseq data (mRNA and totalRNA), from muscle biopsy samples. I have been trying to reproduce the vignette on my data and I was surprised to see that all my adjusted p-values were all at 1. It seems that the vignette is also showing adjusted p-values at 1. I was wondering why this is, and how can this be resolved? The data has been tested already and we know that there are outliers in certain samples.

I am running the script on R 4.4.0 and the installed FRASER version is 2.0.0.

Thank you very much in advance!
Camille

**Comment by vyepez88** [comment]
Hi Camille, how many samples do you have? Usually we obtain pajusted values of 1 with <10 samples.

**Comment by Cam-eraaa** [comment]
Hi, so sorry for the delay in my reply. We also figured it must have been an issue with the number of samples. We tried it with 8 samples and then 16 and both came out with padj values at 1. Hopefully we will have more samples soon. Thank you !

**Comment by vyepez88** [comment]
great to hear, good luck!
